In [1]:
from sklearn import svm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


dataset=pd.read_csv('SolarPrediction_time_aligned.csv',engine='python',nrows=576)
dataset.describe()

UNIXTime    Radiation  Temperature    Pressure    Humidity  \
count    576.000000   576.000000   576.000000  576.000000  576.000000   
mean   40961.618056   291.279601    55.246528   30.439931   77.204861   
std    26041.675520   400.402992     5.226187    0.020173   19.122662   
min        4.000000     1.580000    46.000000   30.400000   28.000000   
25%    16131.750000     2.440000    51.000000   30.420000   65.000000   
50%    40205.500000     3.500000    53.000000   30.440000   75.000000   
75%    63979.250000   641.457500    61.000000   30.460000   97.000000   
max    86107.000000  1073.710000    65.000000   30.470000  103.000000   

       WindDirection(Degrees)       Speed  
count              576.000000  576.000000  
mean               119.847483    5.993681  
std                 68.875549    3.144207  
min                  0.590000    0.000000  
25%                 68.150000    3.370000  
50%                123.895000    5.620000  
75%                158.847500    7.870000  
max                358.480000   18.000000

In [2]:
factor=dataset.drop("Radiation",axis=1)
factor=factor.drop("Data",axis=1)
factor=factor.drop("Time",axis=1)
factor=factor.drop("TimeSunRise",axis=1)
factor=factor.drop("TimeSunSet",axis=1)
pre_data=dataset["Radiation"]
print(factor.head(5))
print(pre_data.head(5))

   UNIXTime  Temperature  Pressure  Humidity  WindDirection(Degrees)  Speed
0         8           51     30.43       103                   77.27  11.25
1       310           51     30.43       103                  153.44   9.00
2      1206           51     30.43       103                  142.04   7.87
3      1505           51     30.43       103                  144.12  18.00
4      1809           51     30.43       103                   67.42  11.25
0    2.58
1    2.83
2    2.16
3    2.21
4    2.25
Name: Radiation, dtype: float64


In [3]:
factor=factor.values
pre_data=pre_data.values

In [4]:
factor=factor.astype(int)
pre_data=pre_data.astype(int)

In [5]:
from sklearn.model_selection import train_test_split
#將iris其中一行去除 species 是標籤 將此標籤的所在行去除 0列1行
#將資料大部分分為train 一部分分為test test_size的比率轉成測值
x_train,x_test,y_train,y_test=train_test_split(factor,pre_data,test_size=0.2,random_state=42)

print(x_train[0:5])
print(x_test[0:5])
#print(y[0:5])

#print(y_train.shape)
#print(y_test.shape)
#print(y)

[[58807    62    30    76    50     3]
 [20705    48    30    86   120     9]
 [73806    53    30    67   126     4]
 [19504    49    30   102   164     9]
 [ 5704    52    30   103   134    10]]
[[81603    51    30    98   170     4]
 [42009    59    30    71    31    11]
 [30608    62    30    30   300     3]
 [77103    54    30   101   129     4]
 [47706    64    30    65   349     7]]


In [6]:
clf=svm.SVC(kernel='rbf',C=1,gamma='auto')
clf.fit(x_train,y_train)

SVC(C=1, gamma='auto')

In [7]:
y_pre=clf.predict(x_test)


In [11]:
print(y_pre)
print(y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2]
[   2 1000  563    2 1029 1043    3    2  146 1026    2  326    2  757
    1  409    2    1    2  773    3  234 1018    2    3  117    3  262
    2   53    2    2  554    3    2  242    2   87    2    2    3  564
 1042  402  497 1012    2    2   18    3    2    7  931    2    2    1
  916 1031   28  183    2   92  857    2   43  633  856  884  331    3
    1  269    2   63   46    2    2    2    3  555 1039  999   11    3
  595    2    3    2  151    2    2  406    2    4 1031 1006    2  899
  989    3  739  463    2   62  939    2    3    3    3    3    2   51
  742    2    3   11]


In [10]:
accuracy_dt=mean_squared_error(y_test,y_pre)
print(accuracy_dt)

214507.47413793104
