In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

row_num=list(range(0,20001))

plant1_gen=pd.read_excel('SolarPrediction_xlsx.xlsx',nrows=5000)


In [2]:
plant1_gen.head(5)#頭五個資料

UNIXTime                   Data      Time  Radiation  Temperature  \
0  1475229326  9/29/2016 12:00:00 AM  23:55:26       1.21           48   
1  1475229023  9/29/2016 12:00:00 AM  23:50:23       1.21           48   
2  1475228726  9/29/2016 12:00:00 AM  23:45:26       1.23           48   
3  1475228421  9/29/2016 12:00:00 AM  23:40:21       1.21           48   
4  1475228124  9/29/2016 12:00:00 AM  23:35:24       1.17           48   

   Pressure  Humidity  WindDirection(Degrees)  Speed TimeSunRise TimeSunSet  
0     30.46        59                  177.39   5.62    06:13:00   18:13:00  
1     30.46        58                  176.78   3.37    06:13:00   18:13:00  
2     30.46        57                  158.75   3.37    06:13:00   18:13:00  
3     30.46        60                  137.71   3.37    06:13:00   18:13:00  
4     30.46        62                  104.95   5.62    06:13:00   18:13:00

In [3]:
plant1_gen.describe()#印出資料內容統計值

UNIXTime    Radiation  Temperature     Pressure    Humidity  \
count  5.000000e+03  5000.000000  5000.000000  5000.000000  5000.00000   
mean   1.474444e+09   244.137338    54.401600    30.436096    77.94500   
std    4.673856e+05   350.818129     5.890675     0.035707    20.78611   
min    1.473619e+09     1.150000    43.000000    30.360000    15.00000   
25%    1.474073e+09     1.240000    50.000000    30.410000    65.00000   
50%    1.474462e+09     9.930000    54.000000    30.440000    84.00000   
75%    1.474842e+09   423.190000    59.000000    30.460000    96.00000   
max    1.475229e+09  1387.170000    71.000000    30.530000   102.00000   

       WindDirection(Degrees)        Speed  
count             5000.000000  5000.000000  
mean               131.469812     5.487334  
std                 86.008711     2.858449  
min                  0.100000     0.000000  
25%                 58.110000     3.370000  
50%                140.925000     5.620000  
75%                175.267500     6.750000  
max                359.930000    20.250000

In [6]:
y=plant1_gen["price actual"]
print(y)

0       65.41
1       64.92
2       64.48
3       59.32
4       56.04
        ...  
4995    55.33
4996    56.26
4997    65.43
4998    68.80
4999    78.33
Name: price actual, Length: 5000, dtype: float64


In [ ]:
i=0
print(len(y))
print(y[0])

python np array由零開始
以下為將一行的內容六個為單位做整理

In [7]:
time_series=np.zeros((len(y)-5,6))
time_series.shape
i=0
j=0

np.set_printoptions(threshold=np.inf)


for i in range(0,len(y)-5):
    for j in range(0,6):
        time_series[i][j]=y[i+j]
        j+=1
    i+=1
    j=0

time_series.shape
#print(time_series)


(4995, 6)

將time series存成excel
需要將二維陣列存成Dataframe

In [8]:

store=pd.DataFrame(time_series,columns=["1","2","3","4","5","6"])
store.to_excel("time_series_of_total_value.xlsx",index=False)

In [9]:
pre=pd.read_excel("time_series_of_total_value.xlsx")
pre.head(5)


1      2      3      4      5      6
0  65.41  64.92  64.48  59.32  56.04  53.63
1  64.92  64.48  59.32  56.04  53.63  51.73
2  64.48  59.32  56.04  53.63  51.73  51.43
3  59.32  56.04  53.63  51.73  51.43  48.98
4  56.04  53.63  51.73  51.43  48.98  54.20

In [10]:
from sklearn.model_selection import train_test_split
x=pre.drop("6",axis=1)
y=pre["6"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
y_train=y_train.astype(int)
y_test=y_test.astype(int)
print(x_test[0:5])
print(x_train[0:5])
print(y[0:5])

          1      2      3      4      5
84    57.03  59.22  58.56  52.07  52.15
3036  63.14  56.37  55.04  54.01  53.95
1497  53.95  53.67  52.27  47.92  51.03
653   48.11  53.35  69.71  79.78  83.04
877   63.06  55.90  56.06  56.61  66.81
          1      2      3      4      5
3173  59.18  59.47  65.58  65.41  66.75
3940  55.56  55.59  55.01  57.20  58.93
2664  49.93  45.19  45.34  46.11  49.76
3949  64.59  61.09  58.19  58.05  62.33
2567  66.33  62.64  59.61  59.71  61.86
0    53.63
1    51.73
2    51.43
3    48.98
4    54.20
Name: 6, dtype: float64


In [11]:
#引入scalar這個函數
from sklearn.preprocessing import StandardScaler
#使用scalar將StandardScaler()存入 用以將數據標準化 均值為零 標準差為1
#以下是標準寫法 將test 及 train 轉為標準化
scalar=StandardScaler()
x_train_scaled=scalar.fit_transform(x_train)
x_test_scaled=scalar.transform(x_test)
print(x_train_scaled.shape)
print(x_train[0:5])
print(x_train_scaled[0:5])

(3996, 5)
          1      2      3      4      5
3173  59.18  59.47  65.58  65.41  66.75
3940  55.56  55.59  55.01  57.20  58.93
2664  49.93  45.19  45.34  46.11  49.76
3949  64.59  61.09  58.19  58.05  62.33
2567  66.33  62.64  59.61  59.71  61.86
[[-0.14595231 -0.12683317  0.3239599   0.3124654   0.41269902]
 [-0.41170783 -0.41304848 -0.45948232 -0.29778792 -0.16940892]
 [-0.82502373 -1.18022354 -1.17621706 -1.12211305 -0.85200864]
 [ 0.2512127  -0.0073309  -0.22378258 -0.234607    0.08368149]
 [ 0.37895154  0.10700769 -0.11853301 -0.11121839  0.04869546]]


K鄰近

In [12]:
#它是K最近鄰（K-Nearest Neighbors，KNN）分類算法的其中一種實現。KNN是一種監督學習算法，通常用於分類任務，根據輸入數據點在特徵空間中的鄰近點來進行分類。
from sklearn.neighbors import KNeighborsClassifier
#classification_report函式用於生成分類任務的報告，其中包括精確度、召回率、F1分數等評估指標，以評估模型的性能。
#accuracy_score函式用於計算分類的準確度，即模型正確分類的樣本比例。通常，這是一個最常用的分類性能指標之一。
from sklearn.metrics import classification_report,accuracy_score
#設定k值 會考慮附近多少個值去做定義 k小:噪聲大 k大:無法捕獲數據細節
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_scaled,y_train)
#將x_test之標準化值投入以上模型進行預測 並存入y_pred_knn中
y_pred_knn=knn.predict(x_test_scaled)
#比對預測及實際值
accuracy_knn=accuracy_score(y_test,y_pred_knn)
print(accuracy_knn)
#精確度（Precision）:指所有預測正確的數據中 實際正確的比率 實際正確/(實際正確+錯誤正確(假陽性)) 忽略對負例的預測
#召回率（Recall）：指所有原本正確值中 被分為正確值 分為正確值/實際正確值 忽略假陽性
#F1分數：F1分數是精確度和召回率的調和平均值，用於綜合考慮精確度和召回率。它適用於不平衡的數據集。
#支持數（Support）：每個類別的樣本數。
#加權平均：報告還包括宏平均（macro average）和加權平均（weighted average）的評估指標，用於全局性能總結。
classification_report_knn=classification_report(y_test,y_pred_knn)
print(classification_report_knn)

0.09309309309309309
              precision    recall  f1-score   support

          13       0.00      0.00      0.00         2
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          17       0.67      0.67      0.67         3
          18       1.00      0.40      0.57         5
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         3
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         2
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         5
       

C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall 

決策樹

In [13]:
#引入決策樹分類器
from sklearn.tree import DecisionTreeClassifier
#42為某種參數
dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_train_scaled,y_train)
y_pred_dt=dt.predict(x_test_scaled)

accuracy_dt=accuracy_score(y_test,y_pred_dt)
classification_report_dt=classification_report(y_test,y_pred_dt)

print(accuracy_dt)
print(classification_report_dt)

0.12512512512512514
              precision    recall  f1-score   support

          13       0.00      0.00      0.00         2
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          17       0.50      0.67      0.57         3
          18       1.00      0.40      0.57         5
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         3
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         2
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         5
          30       0.14      0.33      0.20         3
       

C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall 

隨機森林

In [14]:
from sklearn.ensemble import RandomForestClassifier
#42同樣為用以確保隨機性可重建 n_estimators表決策樹的數量
rf=RandomForestClassifier(random_state=42,n_estimators=100)

rf.fit(x_train_scaled, y_train)

y_pred_rf=rf.predict(x_test_scaled)

accuracy_rf=accuracy_score(y_test,y_pred_rf)
classification_report_rf=classification_report(y_test,y_pred_rf)

print(accuracy_rf)
print(classification_report_rf)

0.13113113113113112
              precision    recall  f1-score   support

          13       0.00      0.00      0.00         2
          15       0.00      0.00      0.00         1
          16       0.25      0.50      0.33         2
          17       0.40      0.67      0.50         3
          18       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         3
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         2
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         5
          30       0.14      0.33      0.20         3
          31       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         1
       

C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall 

下面的是之前測試


In [ ]:
from sklearn.model_selection import train_test_split
#將iris其中一行去除 species 是標籤 將此標籤的所在行去除 0列1行
x=plant1_gen.drop("PLANT_ID",axis=1,)
x=x.drop("DATE_TIME",axis=1)
x=x.drop("TOTAL_YIELD",axis=1)
x=x.drop("SOURCE_KEY",axis=1)


y=plant1_gen["TOTAL_YIELD"]
#將資料大部分分為train 一部分分為test test_size的比率轉成測值
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#y必須為整數
y_train=y_train.astype(int)
y_test=y_test.astype(int)


print(x_test[0:5])
print(x_train[0:5])
print(y[0:5])

#print(y_train.shape)
#print(y_test.shape)
#print(y)