In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pandas import read_csv
import math
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import predict

In [ ]:
dataset=pd.read_csv('SolarRadiationPrediction.csv',engine='python',nrows=576*15)
dataset=dataset.drop("Data",axis=1)
dataset=dataset.drop("Time",axis=1)
target=dataset["Radiation"]
#target=dataset["Radiation"]
dataset.head(5)


UNIXTime  Radiation  Temperature  Pressure  Humidity  \
0         8       2.58           51     30.43       103   
1       310       2.83           51     30.43       103   
2      1206       2.16           51     30.43       103   
3      1505       2.21           51     30.43       103   
4      1809       2.25           51     30.43       103   

   WindDirection(Degrees)  Speed  TimeSunRise  TimeSunSet  
0                   77.27  11.25        22020       67080  
1                  153.44   9.00        22020       67080  
2                  142.04   7.87        22020       67080  
3                  144.12  18.00        22020       67080  
4                   67.42  11.25        22020       67080

In [3]:

dataset=dataset.values
target=target.values



資料交換 這邊為lookback

In [4]:
dataset[:,1]=dataset[:,8]
dataset[:,8]=target[:]
#print(dataset[0,:])
# print(temp1)
# print(temp2)
#target=target.values
#target=target.values

In [5]:
def create_dataset(dataset,look_back):
    dataX,dataY=[],[]
    for i in range(len(dataset)-look_back-1):
        #a=dataset第0行i~i+look_back個
        a=dataset[i:(i+look_back),0:9]
        dataX.append(a)
        dataY.append(dataset[i+look_back,8])
    return np.array(dataX),np.array(dataY)

    

In [6]:
train_size=int(len(dataset)*0.67)
test_size=len(dataset)- train_size
train,test=dataset[0:train_size,:],dataset[train_size:len(dataset),:]


In [7]:
trainX,trainY=create_dataset(train,5)
testX,testY=create_dataset(test,5)
print("train_x: ",trainX.shape)
print("train y: ",trainY.shape)
print("testX: ",testX.shape)
print(trainX[0,:,:])
print(trainY[0])

train_x:  (5782, 5, 9)
train y:  (5782,)
testX:  (2846, 5, 9)
[[8.0000e+00 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 7.7270e+01
  1.1250e+01 2.2020e+04 2.5800e+00]
 [3.1000e+02 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 1.5344e+02
  9.0000e+00 2.2020e+04 2.8300e+00]
 [1.2060e+03 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 1.4204e+02
  7.8700e+00 2.2020e+04 2.1600e+00]
 [1.5050e+03 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 1.4412e+02
  1.8000e+01 2.2020e+04 2.2100e+00]
 [1.8090e+03 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 6.7420e+01
  1.1250e+01 2.2020e+04 2.2500e+00]]
2.15


In [8]:
trainX=trainX.reshape(5782,45)
testX=testX.reshape(2846,45)
trainY=trainY.reshape(len(trainY),1)
testY=testY.reshape(len(testY),1)
print(trainX.shape)
print(trainX[0,:])

(5782, 45)
[8.0000e+00 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 7.7270e+01
 1.1250e+01 2.2020e+04 2.5800e+00 3.1000e+02 6.7080e+04 5.1000e+01
 3.0430e+01 1.0300e+02 1.5344e+02 9.0000e+00 2.2020e+04 2.8300e+00
 1.2060e+03 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 1.4204e+02
 7.8700e+00 2.2020e+04 2.1600e+00 1.5050e+03 6.7080e+04 5.1000e+01
 3.0430e+01 1.0300e+02 1.4412e+02 1.8000e+01 2.2020e+04 2.2100e+00
 1.8090e+03 6.7080e+04 5.1000e+01 3.0430e+01 1.0300e+02 6.7420e+01
 1.1250e+01 2.2020e+04 2.2500e+00]


In [9]:
np.random.seed(7)


dataset=dataset.astype('float32')
target=target.astype('float32')

scalar1=MinMaxScaler(feature_range=(0,1))
scalar2=MinMaxScaler(feature_range=(0,1))
scalar3=MinMaxScaler(feature_range=(0,1))
scalar4=MinMaxScaler(feature_range=(0,1))
#scalar_dim=dataset[:,1]

#target=dataset[:,1]
trainX=scalar1.fit_transform(trainX)
testX=scalar2.fit_transform(testX)
trainY=scalar3.fit_transform(trainY)
testY=scalar4.fit_transform(testY)
#target=target.reshape(len(target),1)
# target=scalar2.fit_transform(target)


In [10]:
# print(trainX)
# print(trainY)
# print(testX)
# print(testY)

In [11]:
# train_size=int(len(dataset)*0.67)
# test_size=len(dataset)- train_size
# train,test=dataset[0:train_size,:],dataset[train_size:len(dataset),:]

# print(train.shape)
# print(train)
# print(test.shape)
#print(test)

一維分析 無lookback

In [12]:
# train_size=int(len(dataset)*0.67)
# test_size=len(dataset)- train_size
# trainX,testX=dataset[0:train_size,:],dataset[train_size:len(dataset),:]
# trainY,testY=target[0:train_size],target[train_size:len(target)]



In [13]:
# np.random.seed(7)


# # dataset=dataset.astype('float32')
# # target=target.astype('float32')
# trainY=trainY.reshape(len(trainY),1)
# testY=testY.reshape(len(testY),1)
# scalar1=MinMaxScaler(feature_range=(0,1))
# scalar2=MinMaxScaler(feature_range=(0,1))
# scalar3=MinMaxScaler(feature_range=(0,1))
# scalar4=MinMaxScaler(feature_range=(0,1))
# #scalar_dim=dataset[:,1]

# #target=dataset[:,1]
# trainX=scalar1.fit_transform(trainX)
# testX=scalar2.fit_transform(testX)
# trainY=scalar3.fit_transform(trainY)
# testY=scalar4.fit_transform(testY)
# #target=target.reshape(len(target),1)
# # target=scalar2.fit_transform(target)


In [14]:
# print(y_train.shape)
# print(y_test.shape)
# print(X_train.shape)
# print(X_test.shape)

使用split

In [15]:
#X_train, X_test, y_train, y_test = train_test_split(dataset, target, test_size=0.2, random_state=42)


有look back
似乎不能用三維 無法look back

In [16]:
# #根據前面幾個資料來看下一步 彙整成look_back行的資料
# #X用以輸入 Y用用以predict
# look_back=5
# trainX,trainY=create_dataset(train,look_back)
# testX,testY=create_dataset(test,look_back)
# print(testX.shape)
# #print(testX)
# print(testY.shape)
# print(trainX.shape)
# print(trainY.shape)


TCN　test

In [17]:
# model=TCN()
# model.fit(trainX,trainY)

In [18]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 初始化決策樹回歸模型
model = DecisionTreeRegressor(max_depth=5,min_samples_split=18,min_samples_leaf=20,max_features='auto')
# 訓練模型
model.fit(trainX,trainY)

C:\Users\wang8\anaconda3\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(


DecisionTreeRegressor(max_depth=5, max_features='auto', min_samples_leaf=20,
                      min_samples_split=18)

In [19]:
y_pred = model.predict(testX)
train_pre=model.predict(trainX)

In [20]:
# print(y_pred.shape)
# print(trainY.shape)
# print(train_pre.shape)
# print(y_test.shape)


In [21]:
print(len(y_pred))
print(len(train_pre))

2846
5782


把預測資料轉換回去

In [22]:
y_pred=np.reshape(y_pred,(len(y_pred),1))
train_pre=np.reshape(train_pre,(len(train_pre),1))
print(y_pred.shape)
# print(y_train.shape)
print(train_pre.shape)
# print(y_test.shape)

(2846, 1)
(5782, 1)


有轉換再用

In [23]:
train_pre=scalar3.inverse_transform(train_pre)
trainY=scalar3.inverse_transform(trainY)
y_pred=scalar4.inverse_transform(y_pred)
testY=scalar4.inverse_transform(testY)


In [24]:
print(train_pre)

[[1.9461126]
 [1.9461126]
 [1.9461126]
 ...
 [1.9461126]
 [1.9461126]
 [1.9461126]]


In [25]:


# 評估模型性能
trainScore=math.sqrt(mean_squared_error(trainY,train_pre))
print('Train Score:%.2f RMSE'%(trainScore))
testScore=math.sqrt(mean_squared_error(testY,y_pred))
print('Test Score:%.2f RMSE'%(testScore))
MAE=mean_absolute_error(testY,y_pred)
print('Test Score:%.2f MAE'%(MAE))

# 可以進一步分析模型的特徵重要性
# feature_importances = model.feature_importances_
# features = X.columns
# feature_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
# feature_df = feature_df.sort_values(by='Importance', ascending=False)


# print("前10個重要特徵：")
# print(feature_df.head(10))

Train Score:89.32 RMSE
Test Score:96.09 RMSE
Test Score:42.70 MAE


In [31]:
mean_squared_error(testY,y_pred)

9232.92742759803

In [26]:
# print(y_train.shape)
# print(train_pre.shape)
# print(y_train)
# print(train_pre)

In [27]:
print(y_pred.shape)
print(testY.shape)
print(testY)
print(y_pred)

(2846, 1)
(2846, 1)
[[  1.22]
 [  1.24]
 [  1.24]
 ...
 [221.67]
 [344.9 ]
 [365.66]]
[[  1.83093731]
 [  1.83093731]
 [  1.83093731]
 ...
 [189.5795614 ]
 [241.7552368 ]
 [383.2660359 ]]


In [28]:
# plt.plot(testY,label='Ground Truth')
# plt.plot(y_pred,label='Prediction')
# #plt.plot(testPredictPlot[0:200],label='Prediction(testing)')
# plt.legend()
# plt.show()

In [29]:
# predict.my_self(testY,y_pred,'Decision Tree')
# predict.score_calculation(testY,y_pred)
# predict.plot_pred(testY,y_pred,'Decision Tree')
# predict.plot_residuals(testY,y_pred,'Decision Tree')